name: Python Application

on:
  push:
    branches: [ "development", "ci_testing" ]
  pull_request:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  build:
    environment: Development
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r .github/workflows/requirements.txt

      - name: Lint with Black
        run: |
          # Check if code is formatted according to Black's style
          black --check .

      - name: Lint with flake8 on tests and backend folders
        run: |
          # Stop the build if there are Python syntax errors or undefined names in tests/ and backend/
          flake8 tests/ backend/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings (for a more lenient check)
          flake8 tests/ backend/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest and generate coverage report
        run: |
          pytest --cov=. --cov-report=term-missing tests/
