name: Python Application

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  build:
    environment: Development
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r .github/workflows/requirements.txt

      - name: Lint with Black
        run: |
          # Check if code is formatted according to Black's style
          black --check .

      - name: Lint with flake8 on tests and backend folders
        run: |
          flake8 tests/ backend/ 

      - name: Test with pytest and generate coverage report
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          pytest --cov=. --cov-report=term-missing tests/
